#ifndef _PLAYER_VERSION_H
#define _PLAYER_VERSION_H
#define PLAYER_VERSION_MAJOR 0
#define PLAYER_VERSION_MINOR 0
#define PLAYER_VERSION_MICRO 1
#define PLAYER_VERSION_REV 0
#define PLAYER_VERSION "0.0.1.0"
#define PLAYER_VERSION_INT (((int32_t)PLAYER_VERSION_MAJOR << 24) | ((int32_t)PLAYER_VERSION_MINOR << 16) | ((int32_t)PLAYER_VERSION_MICRO << 8) | (int32_t)PLAYER_VERSION_REV)
#endif
